/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import client.Flight;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import search.FlightPlan;

/**
 *
 * @author Mike
 */
public class FlightSearchPanel extends javax.swing.JPanel {

    
    JTextPane textPane;
    SearchResultsPanel searchResultsPanel;
    ExpandedFlightPanel expandedFlightPanel;
    
    /**
     * Creates new form FlightSearchPanel
     */
    public FlightSearchPanel() {
        initComponents();
        
        setLayout(new BorderLayout());
        
        textPane = new JTextPane();
        textPane.setFont(new Font("Tahoma", Font.ITALIC, 18));
        textPane.setText("No search results to display");
        textPane.setFocusable(false);
        textPane.setEditable(false);
        textPane.setOpaque(false);
        
        
        add(textPane);
        
        searchResultsPanel = new SearchResultsPanel();
        //add(searchResultsPanel);
        
        expandedFlightPanel = new ExpandedFlightPanel();
        //this.add(searchResultsPanel);
        
    }

    public void updateFlightResults(List<FlightPlan> flightPlanList) {
        removeAll();
        searchResultsPanel.updateFlightResults(flightPlanList);
        add(searchResultsPanel);
    }
    
    public void displayFlightResults()
    {
        removeAll();
        add(searchResultsPanel);
    }
    
    public void displayExpandedFlight()
    {
        removeAll();
        add(expandedFlightPanel);
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
