/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import search.FlightPlan;

/**
 *
 * @author Mike
 */
public class SearchResultsPanel extends javax.swing.JPanel {

    JPanel resultsPanel;
    JScrollPane scrollPane;
    MouseAdapter mouseAdapter;

    /**
     * Creates new form SearchResultsPanel
     *
     * @param adapter
     */
    public SearchResultsPanel() {
        //initComponents();
        mouseAdapter = new FlightPanelMouseAdapter();

        setLayout(new BorderLayout());

        resultsPanel = new JPanel();
        resultsPanel.setLayout(new GridLayout(0, 1));
        resultsPanel.setVisible(true);

        this.add(resultsPanel);
    }

    public void updateFlightResults(List<FlightPlan> flightPlanList) {

        resultsPanel.removeAll();

        for (FlightPlan flightPlan : flightPlanList) {
            JPanel wrappingPanel = new JPanel();
            wrappingPanel.setLayout(new BorderLayout());
            wrappingPanel.add(new FlightPanel(flightPlan, mouseAdapter), BorderLayout.NORTH);
            resultsPanel.add(wrappingPanel);
        }

    }

    public void displayCoachPrices() {
        for (Component resultComponent : resultsPanel.getComponents()) {
            if (resultComponent instanceof JPanel) {
                for (Component panelComponent : ((JPanel) resultComponent).getComponents()) {
                    if (panelComponent instanceof FlightPanel) {
                        ((FlightPanel) panelComponent).displayCoachPrice();
                    }
                }
            }
        }
    }

    public void displayFirstClassPrices() {
        for (Component resultComponent : resultsPanel.getComponents()) {
            if (resultComponent instanceof JPanel) {
                for (Component panelComponent : ((JPanel) resultComponent).getComponents()) {
                    if (panelComponent instanceof FlightPanel) {
                        ((FlightPanel) panelComponent).displayFirstClassPrice();
                    }
                }
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
