/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import client.Flight;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;
import search.FlightPlan;

/**
 *
 * @author Mike
 */
public class SearchResultsPanel extends javax.swing.JPanel {

    JPanel resultsPanel;
    JScrollPane scrollPane;
    JMenuBar menuBar;
    JCheckBoxMenuItem priceMenuItem;
    JCheckBoxMenuItem timeMenuItem;
    
    /**
     * Creates new form SearchResultsPanel
     */
    public SearchResultsPanel() {
        //initComponents();
        
        setLayout(new BorderLayout());
        
        menuBar = new JMenuBar();
        JMenu sortByMenu = new JMenu("Sort By");
        
        priceMenuItem = new JCheckBoxMenuItem(new AbstractAction("Price") {
            @Override
            public void actionPerformed(ActionEvent e) {
                priceMenuItem.setSelected(true);
                timeMenuItem.setSelected(false);
            }
        });
        priceMenuItem.setSelected(true);
        
        timeMenuItem = new JCheckBoxMenuItem(new AbstractAction("Time") {
            @Override
            public void actionPerformed(ActionEvent e) {
                priceMenuItem.setSelected(false);
                timeMenuItem.setSelected(true);
            }
        });

        sortByMenu.add(priceMenuItem);
        sortByMenu.add(timeMenuItem);
        
        
        menuBar.add(sortByMenu);
        this.add(menuBar, BorderLayout.NORTH);
        
        
        resultsPanel = new JPanel();
        resultsPanel.setLayout(new GridLayout(0, 1));
        resultsPanel.setVisible(true);
        /*
        scrollPane = new JScrollPane();
        scrollPane.setLayout(new ScrollPaneLayout());
        scrollPane.getVerticalScrollBar().setUnitIncrement(10);
        scrollPane.setViewportView(resultsPanel);
        this.add(scrollPane);
        */
        this.add(resultsPanel);
    }
    
    
    // Currently does not use flightList, using dummy values
    public void updateFlightResults(List<FlightPlan> flightPlanList) {
        
        resultsPanel.removeAll();

        for(FlightPlan flightPlan : flightPlanList)
        {
            resultsPanel.add(getWrappedPanel(new FlightPanel(flightPlan)));
        }
        
    }
    
    private JPanel getWrappedPanel(FlightPanel flightPanel)
    {
        JPanel wrappingPanel = new JPanel();
        wrappingPanel.setLayout(new BorderLayout());
        wrappingPanel.add(flightPanel,BorderLayout.NORTH);
        return wrappingPanel;
    }
    
    public boolean sortByPriceSelected()
    {
        return priceMenuItem.isSelected();
    }
    
    public boolean sortByTimeSelected()
    {
        return timeMenuItem.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
