/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import search.FlightPlan;

/**
 *
 * @author Mike
 */
public class SearchResultsPanel extends javax.swing.JPanel {

    JPanel resultsPanel;
    JScrollPane scrollPane;
    JMenuBar menuBar;
    JCheckBoxMenuItem priceMenuItem;
    JCheckBoxMenuItem timeMenuItem;

    /**
     * Creates new form SearchResultsPanel
     */
    public SearchResultsPanel() {
        //initComponents();

        setLayout(new BorderLayout());

        menuBar = new JMenuBar();
        JMenu sortByMenu = new JMenu("Sort By");

        priceMenuItem = new JCheckBoxMenuItem(new AbstractAction("Price") {
            @Override
            public void actionPerformed(ActionEvent e) {
                priceMenuItem.setSelected(true);
                timeMenuItem.setSelected(false);
            }
        });
        priceMenuItem.setSelected(true);

        timeMenuItem = new JCheckBoxMenuItem(new AbstractAction("Time") {
            @Override
            public void actionPerformed(ActionEvent e) {
                priceMenuItem.setSelected(false);
                timeMenuItem.setSelected(true);
            }
        });

        sortByMenu.add(priceMenuItem);
        sortByMenu.add(timeMenuItem);

        menuBar.add(sortByMenu);
        this.add(menuBar, BorderLayout.NORTH);

        resultsPanel = new JPanel();
        resultsPanel.setLayout(new GridLayout(0, 1));
        resultsPanel.setVisible(true);

        this.add(resultsPanel);
    }

    public void updateFlightResults(List<FlightPlan> flightPlanList) {

        resultsPanel.removeAll();

        for (FlightPlan flightPlan : flightPlanList) {
            resultsPanel.add(getWrappedPanel(new FlightPanel(flightPlan)));
        }

    }

    public void displayCoachPrices() {
        for (Component resultComponent : resultsPanel.getComponents()) {
            if (resultComponent instanceof JPanel) {
                for (Component panelComponent : ((JPanel)resultComponent).getComponents()) {
                    if (panelComponent instanceof FlightPanel) {
                        ((FlightPanel) panelComponent).displayCoachPrice();
                    }
                }
            }
        }
    }

    public void displayFirstClassPrices() {
        for (Component resultComponent : resultsPanel.getComponents()) {
            if (resultComponent instanceof JPanel) {
                for (Component panelComponent : ((JPanel)resultComponent).getComponents()) {
                    if (panelComponent instanceof FlightPanel) {
                        ((FlightPanel) panelComponent).displayFirstClassPrice();
                    }
                }
            }
        }
    }

    private JPanel getWrappedPanel(FlightPanel flightPanel) {
        JPanel wrappingPanel = new JPanel();
        wrappingPanel.setLayout(new BorderLayout());
        wrappingPanel.add(flightPanel, BorderLayout.NORTH);
        return wrappingPanel;
    }

    public boolean sortByPriceSelected() {
        return priceMenuItem.isSelected();
    }

    public boolean sortByTimeSelected() {
        return timeMenuItem.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
